#!/bin/sh
set -e

if [[ "$1" = "--h" ]] ; then
   echo "Searches for and checks out the latest tag.";
   exit 1;
fi

[ -d .git ] || git rev-parse --is-inside-work-tree > /dev/null 2>&1 || ( echo "Current directory is not a git folder." && exit 1);

git fetch --tags
latestTag=$(git describe --tags `git rev-list --tags --max-count=1`)
git checkout $latestTag
