#!/bin/sh
set -e
masterBranch="master"

((!$#)) && echo No issue id, command ignored! && echo "  - git issue <issue id>" && exit 1

if [[ "$1" = "--h" ]] ; then
   echo "Creates an issue branch at the latest commit on $masterBranch and checks it out.";
   echo "Unlike feature branches, issue branches will directly be merged into $masterBranch when finished."
   echo "  - git issue <workitem id>";
   exit 1;
fi

[ -d .git ] || git rev-parse --is-inside-work-tree > /dev/null 2>&1 || ( echo "Current directory is not a git folder." && exit 1);

numericRegex="^[.0-9]+$"
if [[ "$1" =~ $numericRegex ]] ; then
	echo Starting issue $1
	git checkout -b issue/$1 $masterBranch
else
	echo "Issue names have to be numeric (e.g. the work item id related to them)"
fi
