#!/bin/sh
set -e
masterBranch="master"

((!$#)) && echo No release name, command ignored! && echo "  - git release <version> <startingPoint>" && exit 1

if [[ "$1" = "--h" ]] ; then
   echo "Creates a release branch at either the latest commit on $masterBranch or when supplied the <startingPoint> and checks it out.";
   echo "  - git release <version> <startingPoint>";
   exit 1;
fi

[ -d .git ] || git rev-parse --is-inside-work-tree > /dev/null 2>&1 || ( echo "Current directory is not a git folder." && exit 1);

numericRegex="^[.0-9]+$"
if ! [[ "$1" =~ $numericRegex ]] ; then
   echo error: Not a numeric version
   exit 1
fi


head=$masterBranch
if [ "$2" = "" ]; then
	echo branching from latest commit on $head
else
	head=$2
	echo branching from requested starting point: $head
fi

echo Starting release $1
git checkout -b release/$1 $head

# Tag just created feature branch with lightweight tag: v$version-$feature
# This tag should not be merged to master (it's a branch local tag)
# tag is going to be used
branch=$(git rev-parse --abbrev-ref HEAD)
branchName=$(echo $branch| cut -d'/' -f 1)
branchVersion=$(echo $branch| cut -d'/' -f 2 |sed 's/^v//g')
VERSION="v${branchVersion}-rc"
echo "Tagging branch release/$1 wish version $VERSION as release candidate (rc)"
echo "Please note: it's a lightweight tag to track version, while we working on release"
echo "             final tag for release should be annotated: v$branchVersion"
git tag "$VERSION"
