#!/bin/sh
#set -e

if [[ "$1" = "--h" ]] ; then
   echo "Opens the current git repo on the web.";
   exit 1;
fi

[ -d .git ] || git rev-parse --is-inside-work-tree > /dev/null 2>&1 || ( echo "Current directory is not a git folder." && exit 1);

originUrl=$(git config --get remote.origin.url)
REPO_URL=`git config --get remote.origin.url | sed -Ene's#git@github.com:([^[:space:]]*)\.git#https://github.com/\1#p'`
echo $REPO_URL

case $( uname -s ) in
  Darwin)  open='open';;
  MINGW*)  open='start';;
  MSYS*)   open='start';;
  CYGWIN*) open='cygstart';;
  *)       open='xdg-open';;
esac

# open it in a browser
${BROWSER:-$open} "$REPO_URL"
