#!/bin/sh
set -e
masterBranch="master"

if [[ "$1" = "--h" ]] ; then
   echo "Checks out latest commit on $masterBranch.";
   exit 1;
fi

[ -d .git ] || git rev-parse --is-inside-work-tree > /dev/null 2>&1 || ( echo "Current directory is not a git folder." && exit 1);

git checkout $masterBranch
