#!/bin/sh
set -e
masterBranch="master"

((!$#)) && echo No feature name, command ignored! && echo "  - git feature <name>" && exit 1

if [[ "$1" = "--h" ]] || [[ "$1" = "help" ]] ; then
   echo "Creates a feature branch at the latest commit on $masterBranch and checks it out.";
   echo "Feature branches will create a pull request to $masterBranch when finished."
   echo "  - git feature <name>";
   exit 1;
fi

[ -d .git ] || git rev-parse --is-inside-work-tree > /dev/null 2>&1 || ( echo "Current directory is not a git folder." && exit 1);

echo Starting feature $1
git checkout -b feature/$1 $masterBranch

# Tag just created feature branch with lightweight tag: v$version-$feature
# This tag should not be merged to master (it's a branch local tag)
# tag is going to be used
branch=$(git rev-parse --abbrev-ref HEAD)
branchName=$(echo $branch| cut -d'/' -f 1 | sed 's/[^\w\d]//g')
branchVersion=$(git describe --tags | cut -d'-' -f 1 |sed 's/^v//g')
git tag "v$branchVersion-$branchName"
